export const products = [
  {
    id: 1,
    name: "Cashew Supreme",
    image: "/images/products/product-1.png",
    category: "cat-1",
    price: 250,
    rating: 4,
    description: "A supreme blend of high-quality cashews for a delightful snacking experience.",
  },
  {
    id: 2,
    name: "Apple Cashew Delight",
    image: "/images/products/product-2.png",
    category: "cat-2",
    price: 100,
    rating: 5,
    description: "Delightful combination of apples and cashews, perfect for a refreshing treat.",
  },
  {
    id: 3,
    name: "Cashew Citrus Splash",
    image: "/images/products/product-3.png",
    category: "cat-3",
    price: 100,
    rating: 5,
    description: "Experience a splash of citrus with this delightful cashew snack.",
  },
  {
    id: 4,
    name: "Crunchy Cashew Fusion",
    image: "/images/products/product-4.png",
    category: "cat-2",
    price: 100,
    rating: 5,
    description: "A fusion of crunchy goodness and premium cashews for a satisfying snack.",
  },
  {
    id: 5,
    name: "Cashew Berry Bliss",
    image: "/images/products/product-5.png",
    category: "cat-3",
    price: 100,
    rating: 5,
    description: "Indulge in the blissful combination of cashews and berries in every bite.",
  },
  {
    id: 6,
    name: "Spicy Cashew Tango",
    image: "/images/products/product-6.png",
    category: "cat-3",
    price: 100,
    rating: 5,
    description: "Experience the bold flavors of spice in this exciting cashew tango.",
  },
  {
    id: 7,
    name: "Cashew Mango Fusion",
    image: "/images/products/product-7.png",
    category: "cat-1",
    price: 100,
    rating: 5,
    description: "A fusion of cashews and mango for a tropical snacking delight.",
  },
  {
    id: 8,
    name: "Cashew Vanilla Dream",
    image: "/images/products/product-8.png",
    category: "cat-2",
    price: 100,
    rating: 5,
    description: "Indulge in the dreamy flavors of vanilla-infused cashews.",
  },
  {
    id: 9,
    name: "Savory Cashew Delight",
    image: "/images/products/product-9.png",
    category: "cat-2",
    price: 100,
    rating: 5,
    description: "Delight your taste buds with this savory and delightful cashew treat.",
  },
  {
    id: 10,
    name: "Zesty Cashew Splash",
    image: "/images/products/product-10.png",
    category: "cat-3",
    price: 100,
    rating: 5,
    description: "Experience a zesty splash of flavor with these delightful cashews.",
  },
  {
    id: 11,
    name: "Cashew Chocolate Indulgence",
    image: "/images/products/product-11.png",
    category: "cat-2",
    price: 100,
    rating: 5,
    description: "Indulge in the rich and decadent chocolate-infused cashew indulgence.",
  },
  {
    id: 12,
    name: "Cashew Honey Harmony",
    image: "/images/products/product-12.png",
    category: "cat-1",
    price: 100,
    rating: 5,
    description: "Experience the harmonious blend of honey and cashews in every bite.",
  },
  {
    id: 13,
    name: "Citrus Burst Cashew",
    image: "/images/products/product-13.png",
    category: "cat-2",
    price: 100,
    rating: 5,
    description: "Bursting with citrusy goodness, these cashews offer a refreshing snacking experience.",
  },
  {
    id: 14,
    name: "Cashew Berry Delight",
    image: "/images/products/product-14.png",
    category: "cat-3",
    price: 100,
    rating: 5,
    description: "Delight in the berry goodness combined with premium cashews for a delightful treat.",
  },
  {
    id: 15,
    name: "Cashew Vanilla Elegance",
    image: "/images/products/product-15.png",
    category: "cat-1",
    price: 100,
    rating: 5,
    description: "Elegantly infused with vanilla, these cashews offer a sophisticated snacking experience.",
  },
  {
    id: 16,
    name: "Cashew Caramel Bliss",
    image: "/images/products/product-16.png",
    category: "cat-2",
    price: 100,
    rating: 5,
    description: "Indulge in the blissful combination of caramel and premium cashews.",
  },
  {
    id: 17,
    name: "Almond Delight",
    image: "/images/products/product-17.png",
    category: "cat-1",
    price: 300,
    rating: 4,
    description: "Delight in the richness of almonds with this delightful snacking option.",
  },
  {
    id: 18,
    name: "Smooth Almond Bliss",
    image: "/images/products/product-18.png",
    category: "cat-2",
    price: 150,
    rating: 4.5,
    description: "Experience the smooth and blissful taste of almonds with this delightful snack.",
  },
  {
    id: 19,
    name: "Pistachio Crunch Delight",
    image: "/images/products/product-19.png",
    category: "cat-3",
    price: 200,
    rating: 4.7,
    description: "Indulge in the delightful crunchiness of pistachios with this satisfying snacking option.",
  },
  {
    id: 20,
    name: "Rich Walnut Butter",
    image: "/images/products/product-20.png",
    category: "cat-1",
    price: 280,
    rating: 4.2,
    description: "Rich and buttery walnut spread for a luxurious snacking experience.",
  },
  {
    id: 21,
    name: "Hazelnut Joy Spread",
    image: "/images/products/product-21.png",
    category: "cat-3",
    price: 180,
    rating: 4.8,
    description: "Spread the joy with this delightful hazelnut spread, perfect for any occasion.",
  },
];
