export const products = [
    {
        id: 1,
        name: "Cashew Supreme",
        image: "/images/products/product-1.png",
        category: "cat-1",
        price: 250,
        rating: 4,
      },
      {
        id: 2,
        name: "Apple Cashew Delight",
        image: "/images/products/product-2.png",
        category: "cat-2",
        price: 100,
        rating: 5,
      },
      {
        id: 3,
        name: "Cashew Citrus Splash",
        image: "/images/products/product-3.png",
        category: "cat-3",
        price: 100,
        rating: 5,
      },
      {
        id: 4,
        name: "Crunchy Cashew Fusion",
        image: "/images/products/product-4.png",
        category: "cat-2",
        price: 100,
        rating: 5,
      },
      {
        id: 5,
        name: "Cashew Berry Bliss",
        image: "/images/products/product-5.png",
        category: "cat-3",
        price: 100,
        rating: 5,
      },
      {
        id: 6,
        name: "Spicy Cashew Tango",
        image: "/images/products/product-6.png",
        category: "cat-3",
        price: 100,
        rating: 5,
      },
      {
        id: 7,
        name: "Cashew Mango Fusion",
        image: "/images/products/product-7.png",
        category: "cat-1",
        price: 100,
        rating: 5,
      },
      {
        id: 8,
        name: "Cashew Vanilla Dream",
        image: "/images/products/product-8.png",
        category: "cat-2",
        price: 100,
        rating: 5,
      },
      {
        id: 9,
        name: "Savory Cashew Delight",
        image: "/images/products/product-9.png",
        category: "cat-2",
        price: 100,
        rating: 5,
      },
      {
        id: 10,
        name: "Zesty Cashew Splash",
        image: "/images/products/product-10.png",
        category: "cat-3",
        price: 100,
        rating: 5,
      },
      {
        id: 11,
        name: "Cashew Chocolate Indulgence",
        image: "/images/products/product-11.png",
        category: "cat-2",
        price: 100,
        rating: 5,
      },
      {
        id: 12,
        name: "Cashew Honey Harmony",
        image: "/images/products/product-12.png",
        category: "cat-1",
        price: 100,
        rating: 5,
      },
      {
        id: 13,
        name: "Citrus Burst Cashew",
        image: "/images/products/product-13.png",
        category: "cat-2",
        price: 100,
        rating: 5,
      },
      {
        id: 14,
        name: "Cashew Berry Delight",
        image: "/images/products/product-14.png",
        category: "cat-3",
        price: 100,
        rating: 5,
      },
      {
        id: 15,
        name: "Cashew Vanilla Elegance",
        image: "/images/products/product-15.png",
        category: "cat-1",
        price: 100,
        rating: 5,
      },
      {
        id: 16,
        name: "Cashew Caramel Bliss",
        image: "/images/products/product-16.png",
        category: "cat-2",
        price: 100,
        rating: 5,
      },
      {
        id: 17,
        name: "Almond Delight",
        image: "/images/products/product-17.png",
        category: "cat-1",
        price: 300,
        rating: 4,
      },
      {
        id: 18,
        name: "Smooth Almond Bliss",
        image: "/images/products/product-18.png",
        category: "cat-2",
        price: 150,
        rating: 4.5,
      },
      {
        id: 19,
        name: "Pistachio Crunch Delight",
        image: "/images/products/product-19.png",
        category: "cat-3",
        price: 200,
        rating: 4.7,
      },
      {
        id: 20,
        name: "Rich Walnut Butter",
        image: "/images/products/product-20.png",
        category: "cat-1",
        price: 280,
        rating: 4.2,
      },
      {
        id: 21,
        name: "Hazelnut Joy Spread",
        image: "/images/products/product-21.png",
        category: "cat-3",
        price: 180,
        rating: 4.8,
      },
]